# Generated by Django 4.1.3 on 2022-11-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-creation"]},
        ),
    ]
